#EVENTS FUCNTION
import pygame

# Define custom events
JOY_LEFT_EVENT = pygame.USEREVENT + 1
JOY_RIGHT_EVENT = pygame.USEREVENT + 2
JOY_UP_EVENT = pygame.USEREVENT + 3
JOY_DOWN_EVENT = pygame.USEREVENT + 4
BUTTON_1_EVENT = pygame.USEREVENT + 5
BUTTON_2_EVENT = pygame.USEREVENT + 6

